W6D5/cats99/config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :cats 
end

W6D5/cats99/app/models/cat.rb
class Cat < ApplicationRecord
    include ActionView::Helpers::DateHelper

    COLORS = %w(red green yellow blue orange)
    validates :birthdate, :color, :name, :sex, :description, presence: true
    validates :color, inclusion: { in: COLORS,
        message: "%{value} is not a valid color"}
    validates :sex, inclusion: { in: %w(M F)}

    def age
        time_ago_in_words(birthdate)
    end
end

W6D5/cats99/app/controllers/cats_controller.rb
class CatsController < ApplicationController
    def index 
        @cats = Cat.all
        render :index
    end

    def show
        @cat = Cat.find(params[:id])
        render :show 
    end

    def new
        @cat = Cat.new
        render :new
    end

    def create
        @cat = Cat.new(cat_params)
        if @cat.save 
            redirect_to cat_url(@cat)
        else
            render :new
        end
    end

    def edit
        @cat = Cat.find(params[:id])
        render :edit
    end

    def update
        @cat = Cat.find(params[:id])
        if @cat.update(cat_params)
            redirect_to cat_url(@cat)
        else
            render json: @cat.errors.full_messages, status: 422
        end
    end
    private
    def cat_params
        params.require(:cat).permit(:birthdate,:color,:name,:sex,:description)
    end
end

W6D5/cats99/app/views/cats/_form.html.erb
<% if type == :new %>
    <% action_url = cats_url %>
    <% button_text = "Create Cat" %>
<% else %>
    <% action_url = cat_url(cat) %>
    <% button_text = "Edit Cat" %>
<% end %>


<form action="<%= action_url %>" method="POST">
    <%if type == :edit%>
    <input type="hidden" name="_method" value="PATCH">
    <%end%>
    <label for="name">Name:
        <input type="text" name="cat[name]" value="<%= cat.name %>">
    </label>
    <br>
    <label for="sex">Sex:
        <br>
        <input type="radio" name="cat[sex]" value="M" <%= cat.sex == 'M' ? "checked" : "" %>>
        <label>M</label>
        <br>
        <input type="radio" name="cat[sex]" value="F" <%= cat.sex == 'F' ? "checked" : "" %>>
        <label>F</label>
    </label>
    <br>
    <label for="color">Choose a color:</label>
    <select name="cat[color]">
        <option disabled selected="true">Please choose a color</option>
        <% Cat::COLORS.each do |color| %>
            <option value="<%= color %>" <%= cat.color == color ? "selected" : "" %> ><%= color.capitalize %></option>
        <% end %>
    </select>
    <br>
    <label for="birthdate">Choose your birthday:</label>
    <input type="date" name="cat[birthdate]" min="2000-01-01" max="<%= Date.today %>" value="<%= cat.birthdate %>">
    <br><br>
    <label for="description">Write about yourself:</label>
    <textarea name="cat[description]"><%= cat.description %></textarea>
    <br>
    <input type="submit" value="<%= button_text %>">
</form>

W6D5/cats99/app/views/cats/edit.html.erb
<!--
<form action="<%#= cat_url(@cat) %>" method="POST">
    <input type="hidden" name="_method" value="PATCH">
    <label for="name">Name:
        <input type="text" name="cat[name]" value="<%#= @cat.name %>">
    </label>
    <br>
    <label for="sex">Sex:
        <br>
        <input type="radio" name="cat[sex]" value="M" <%#= @cat.sex == 'M' ? "checked" : "" %>>
        <label>M</label>
        <br>
        <input type="radio" name="cat[sex]" value="F" <%#= @cat.sex == 'F' ? "checked" : "" %>>
        <label>F</label>
    </label>
    <br>
    <label for="color">Choose a color:</label>
    <select name="cat[color]">
        <option disabled selected="true">Please choose a color</option>
        <%# Cat::COLORS.each do |color| %>
            <option value="<%#= color %>" <%#= @cat.color == color ? "selected" : "" %> ><%#= color.capitalize %></option>
        <%# end %>
    </select>
    <br>
    <label for="birthdate">Choose your birthday:</label>
    <input type="date" name="cat[birthdate]" min="2000-01-01" max="<%# Date.today %>" value=<%#= @cat.birthdate %>>
    <br><br>
    <label for="description">Write about yourself:</label>
    <textarea name="cat[description]"><%#= @cat.description %></textarea>
    <br>
    <input type="submit" value="Edit Cat!">
</form>
-->

<%= render "form", cat: @cat, type: :edit %>

W6D5/cats99/app/views/cats/index.html.erb
<ul>
    <% @cats.each do |cat| %>
        <li><a href="<%= cat_url(cat) %>"><%= cat.name %></a></li>
        <li><%= cat.birthdate %></li>
        <li><%= cat.color %></li>
        <li><%= cat.sex %></li>
        <li><%= cat.description %></li>
        <br>
    <% end %>
</ul>
 
 

W6D5/cats99/app/views/cats/new.html.erb
<!--<
<form action="<%#= cats_url %>" method="POST">
<label for="name">Name:
    <input type="text" name="cat[name]" value="<%#= @cat.name %>">
</label>
<br>
<label for="sex">Sex:
    <br>
    <input type="radio" name="cat[sex]" value="M">
    <label>M</label>
    <br>
    <input type="radio" name="cat[sex]" value="F">
    <label>F</label>
</label>
<br>
<label for="color">Choose a color:</label>
<select name="cat[color]">
    <option disabled selected="true">Please choose a color</option>
    <%# Cat::COLORS.each do |color| %>
        <option value="<%#= color %>"><%#= color.capitalize %></option>
    <%# end %>
</select>
<br>
<label for="birthdate">Choose your birthday:</label>
<input type="date" name="cat[birthdate]" min="2000-01-01" max="<%#= Date.today %>">
<br><br>
<label for="description">Write about yourself:</label>
<textarea name="cat[description]"></textarea>
<br>
<input type="submit" value="Create Cat!">
</form>
-->

<%= render "form", cat: @cat, type: :new %>

W6D5/cats99/app/views/cats/show.html.erb
<table>
    <thead>
        <tr>
            <th colspan="2"><%=@cat.name%></th>
        </tr>
    </thead>
    <tbody>
        <tr>
            <td>Birthday</td>
            <td><%= @cat.birthdate %></td>
        </tr>
        <tr>
            <td>Color</td>
            <td><%= @cat.color %></td>
        </tr>
        <tr>
            <td>Sex</td>
            <td><%= @cat.sex %></td>
        </tr>
        <tr>
            <td>Description</td>
            <td><%= @cat.description %></td>
        </tr>
    </tbody>
</table>